### ISSUE TITLE
Reduce transaction costs by 1/8

### ISSUE THREAD

**Issue by o0ragman0o** [tiendatiowa/punch-clock#1]
The costs of this contract could be cut by almost 1/8th by using `uint64` in the struct rather than just `uint`.

Given that each member's timecards are held in an array, using `uint64` allows for 4 timstamps per slot rather than two timestamps in two slots

```
    struct PunchCard {
        uint64 timeIn; // time the person gets in, unix timestamp
        uint64 timeOut; // time the person gets out, unix timestamp
    }
```

**Comment by tiendatiowa** [comment]
Thanks @o0ragman0o for the 1st issue! Yes, `uint` is alias for `uint256`, which is a waste of space for storing a timestamp. Using `uint64` will save space and cost.
